global_costmap:
  global_frame: /map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 1.0
  static_map: true
  inflation_radius: 10.0
  cost_scaling_factor: 5.0
# footprint_padding: 0.15
  footprint_padding: 0.6

planner_patience: 3.0
controller_patience: 3.0
